# Generated by Django 5.0.1 on 2024-04-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
    ]
