# Generated by Django 5.0.1 on 2024-04-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_news', '0003_аrticles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Аrticles',
        ),
    ]
