# Generated by Django 5.0.1 on 2024-04-14 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_news', '0004_delete_аrticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Содержание статьи')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='article_photos/')),
                ('author', models.CharField(max_length=255, verbose_name='Автор статьи')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации статьи')),
                ('tags', models.ManyToManyField(to='game_news.articletag', verbose_name='Теги статьи')),
            ],
        ),
    ]
