# Generated by Django 5.0.1 on 2024-02-07 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название темы')),
                ('content', models.TextField(verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_photos/')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('tags', models.ManyToManyField(to='game_news.tag', verbose_name='Теги')),
            ],
        ),
    ]
